
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run script with secret
        env:
          MY_API_TOKEN: ${{ secrets.MY_CUSTOM_TOKEN }} # Mapping the secret
        run: python myscript.py
